package net.juancarlosfernandez.myfilms.domain;

import java.util.Date;

public class Film {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILM.ID_FILM
     *
     * @mbggenerated Fri Dec 10 20:19:30 CET 2010
     */
    private Long idFilm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILM.TITLE
     *
     * @mbggenerated Fri Dec 10 20:19:30 CET 2010
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILM.LOCATION
     *
     * @mbggenerated Fri Dec 10 20:19:30 CET 2010
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILM.FILENAME
     *
     * @mbggenerated Fri Dec 10 20:19:30 CET 2010
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILM.LAST_CHANGE
     *
     * @mbggenerated Fri Dec 10 20:19:30 CET 2010
     */
    private Date lastChange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILM.IMAGE
     *
     * @mbggenerated Fri Dec 10 20:19:30 CET 2010
     */
    private byte[] image;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILM.ID_FILM
     *
     * @return the value of FILM.ID_FILM
     *
     * @mbggenerated Fri Dec 10 20:19:30 CET 2010
     */
    public Long getIdFilm() {
        return idFilm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILM.ID_FILM
     *
     * @param idFilm the value for FILM.ID_FILM
     *
     * @mbggenerated Fri Dec 10 20:19:30 CET 2010
     */
    public void setIdFilm(Long idFilm) {
        this.idFilm = idFilm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILM.TITLE
     *
     * @return the value of FILM.TITLE
     *
     * @mbggenerated Fri Dec 10 20:19:30 CET 2010
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILM.TITLE
     *
     * @param title the value for FILM.TITLE
     *
     * @mbggenerated Fri Dec 10 20:19:30 CET 2010
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILM.LOCATION
     *
     * @return the value of FILM.LOCATION
     *
     * @mbggenerated Fri Dec 10 20:19:30 CET 2010
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILM.LOCATION
     *
     * @param location the value for FILM.LOCATION
     *
     * @mbggenerated Fri Dec 10 20:19:30 CET 2010
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILM.FILENAME
     *
     * @return the value of FILM.FILENAME
     *
     * @mbggenerated Fri Dec 10 20:19:30 CET 2010
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILM.FILENAME
     *
     * @param filename the value for FILM.FILENAME
     *
     * @mbggenerated Fri Dec 10 20:19:30 CET 2010
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILM.LAST_CHANGE
     *
     * @return the value of FILM.LAST_CHANGE
     *
     * @mbggenerated Fri Dec 10 20:19:30 CET 2010
     */
    public Date getLastChange() {
        return lastChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILM.LAST_CHANGE
     *
     * @param lastChange the value for FILM.LAST_CHANGE
     *
     * @mbggenerated Fri Dec 10 20:19:30 CET 2010
     */
    public void setLastChange(Date lastChange) {
        this.lastChange = lastChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILM.IMAGE
     *
     * @return the value of FILM.IMAGE
     *
     * @mbggenerated Fri Dec 10 20:19:30 CET 2010
     */
    public byte[] getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILM.IMAGE
     *
     * @param image the value for FILM.IMAGE
     *
     * @mbggenerated Fri Dec 10 20:19:30 CET 2010
     */
    public void setImage(byte[] image) {
        this.image = image;
    }
}